config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "home/about" => "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  devise_for :users
  resources :books
  resources :users, onry: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: { minimum: 1, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  #has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 def new
  @book = Book.new
 end

 def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  @user = @book.user
  if @book.save
   flash[:notice] = "You have created book successfully."
   redirect_to book_path(@book.id)
  else
   @books = Book.all
   render :index
  end
 end

 def index
  @books = Book.all
  @book = Book.new
  @user = User.find(current_user.id)
 end

 def show
  @book = Book.find(params[:id])
  @user = @book.user
 end

 def edit
  @book = Book.find(params[:id])
  if @book.user == current_user
   render :edit
  else
   redirect_to books_path
  end
 end

 def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
   flash[:notice] = "You have updated book successfully."
   redirect_to book_path(@book.id)
  else
   render :edit
  end
 end

 def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to books_path
 end

 private

 def book_params
  params.require(:book).permit(:title, :body)
 end

end

app/controllers/concerns/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(curent_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<div class="col-md-3">
  <h2>User info</h2>

  <%= image_tag user.get_profile_image(100,100) %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <% if user.name != "guestuser" %>
  <div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <% end %>

  <h2 class="mt-3">New book</h2>
    <div>
      <%= form_with model: Book.new do |f| %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %><br>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
</div>

app/views/books/books.html.erb
<h2>Books</h2>

app/views/books/detail.html.erb
<h2>Book details</h2>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3>
            <%= @book.errors.count %> error prohibited this obj from being saved:
          </h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %><br>
          <%= f.text_area :body, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.submit 'Update Book', class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      <%= "|" %>
      <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <%= flash[:notice] %>
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3>
        <%= @book.errors.count %>prohibited this obj from being saved:
      </h3>
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <%= render 'books', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </th>
            <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </th>
            <th><%= book.body %></th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <%= flash[:notice] %>
  <div class="row">
    <%= render 'books', book: @book, user: @user%>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100,100) %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book.id) %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong>
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <%= flash[:notice] %>
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-x1-6">
      <div>
        <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers,</strong>
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!<p>
      </div>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class:"btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        <div class="row">
          <%= link_to "Log in", new_user_session_path,
          class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path,
              class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <buttom class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </buttom>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                 <i class="fas fa-home" style="color: white;"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users" style="color: white;"></i> Users
                <% end %>
               </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open" style="color: white;"></i> Books
                <% end %>
              </li>
              <li class="nav-item" style="color: white;">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home" style="color: white"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link" style="color: white"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus" style="color: white"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt" style="color: white;"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <div id="error_explanation">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>
          <h3>
            prohibited this obj from being saved:
          </h3>
          <ul>
            <%= @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

        <%= form_with model: @user do |f| %>
          <div>
          <label for="inoutName">Name</label>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="inputImage">Image</label><br>
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="inputIntroduction">Introduction</label>
            <%= f.text_field :introduction, class:"form-control"  %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= flash[:notice] %>
  <div class="row">
    <%= render 'books/books', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <th><%= image_tag user.get_profile_image(100,100) %></th>
            <th><%= user.name %></th>
            <th><%= link_to  "Show", user_path(user.id) %></th>
            <th></th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <%= flash[:notice] %>
  <div class="row">
    <%= render 'books/books', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </th>
            <th><%= link_to book.title, book_path(book.id) %></th>
            <th><%= book.body %></th>
            <th></th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>